name: IAM Definition Update

on:
  schedule:
  # Run on the first day of the month
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: install deps
        run: pip install requests schema PyYAML click click_log beautifulsoup4
      - name: install policy_sentry
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      - name: Run initialize
        run: |
          python .github/scripts/update_data.py
          if [[ $(du -m /tmp/.policy_sentry/iam-definition.json | cut -f1) -lt 3 ]]; then
            echo "File size is less than 3 MB, something is wrong with this update"
            exit 1
          fi
          cp -f /tmp/.policy_sentry/iam-definition.json $(pwd)/policy_sentry/shared/data/iam-definition.json
          cp -rf /tmp/.policy_sentry/data/docs $(pwd)/policy_sentry/shared/data/
      - name: PR if files were updated
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update database
          title: 'Updates database'
          body: This is an automated PR created because AWS IAM definitions have changed.
